---
version: "3.9"  # optional since v1.27.0
services:
  rundeck:
    image: panubo/rundeck:latest
    ports:
      - "4440:4440"
    volumes:
      - ./test/config:/config
      - rundeck-lib-data:/var/lib/rundeck/data
      - rundeck-lib-logs:/var/lib/rundeck/var
      - rundeck-lib-logs:/var/lib/rundeck/logs
      - rundeck-home:/home/rundeck
      - rundeck-var:/var/rundeck
      - rundeck-logs:/var/log/rundeck

volumes:
  rundeck-lib-data: {}
  rundeck-lib-logs: {}
  rundeck-home: {}
  rundeck-var: {}
  rundeck-logs: {}
